POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE4ZDU3NzkxMzgwMjEzNzgyMTJlOTEiLCJpYXQiOjE2MjkwMTc2NDMsImV4cCI6MTYyOTAzNTY0M30.bEpdE6NjYXIWJtquq9zApu9fLesBw7C6OxGk-nVse28

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": "5"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE4ZDU3NzkxMzgwMjEzNzgyMTJlOTEiLCJpYXQiOjE2MjkwMTc0NzgsImV4cCI6MTYyOTAzNTQ3OH0.epVJiW66JL_UQo-fBaYrSyRel7Tme2FJfil3YvlN2u0

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": "7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOGQ1N2I5MTM4MDIxMzc4MjEyZTk1IiwiaWF0IjoxNjI5MDE3NjkxLCJleHAiOjE2MjkwMzU2OTF9.LyKnEJ7tEbqMHRJgVUFyf44zkO9OqpJeEj0-NqpkDSU

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": "12"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOGQ1N2I5MTM4MDIxMzc4MjEyZTk1IiwiaWF0IjoxNjI5MDE3NjkxLCJleHAiOjE2MjkwMzU2OTF9.LyKnEJ7tEbqMHRJgVUFyf44zkO9OqpJeEj0-NqpkDSU

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
  "likes": "10"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOGQ1N2I5MTM4MDIxMzc4MjEyZTk1IiwiaWF0IjoxNjI5MDE3NjkxLCJleHAiOjE2MjkwMzU2OTF9.LyKnEJ7tEbqMHRJgVUFyf44zkO9OqpJeEj0-NqpkDSU

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": "0"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOGQ1N2I5MTM4MDIxMzc4MjEyZTk1IiwiaWF0IjoxNjI5MDE3NjkxLCJleHAiOjE2MjkwMzU2OTF9.LyKnEJ7tEbqMHRJgVUFyf44zkO9OqpJeEj0-NqpkDSU

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}
