POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE5NWNlM2NiY2Q4YTFkOWEzN2E5YzAiLCJpYXQiOjE2MjkwNTIxMzksImV4cCI6MTYyOTA3MDEzOX0.NlC6hT-kbBMSftlQnwsaTfbJTdJk8zvAngY5HP3NXdE

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": "5"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE5NWNlM2NiY2Q4YTFkOWEzN2E5YzAiLCJpYXQiOjE2MjkwNTIxMzksImV4cCI6MTYyOTA3MDEzOX0.NlC6hT-kbBMSftlQnwsaTfbJTdJk8zvAngY5HP3NXdE

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": "7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTVjZTRjYmNkOGExZDlhMzdhOWM0IiwiaWF0IjoxNjI5MDUyMTU0LCJleHAiOjE2MjkwNzAxNTR9.DJzaDCWmevScIYyEWM36yJoPClOVB5v2Lf97UaD15cI

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": "12"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTVjZTRjYmNkOGExZDlhMzdhOWM0IiwiaWF0IjoxNjI5MDUyMTU0LCJleHAiOjE2MjkwNzAxNTR9.DJzaDCWmevScIYyEWM36yJoPClOVB5v2Lf97UaD15cI

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
  "likes": "10"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTVjZTRjYmNkOGExZDlhMzdhOWM0IiwiaWF0IjoxNjI5MDUyMTU0LCJleHAiOjE2MjkwNzAxNTR9.DJzaDCWmevScIYyEWM36yJoPClOVB5v2Lf97UaD15cI

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": "0"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTVjZTRjYmNkOGExZDlhMzdhOWM0IiwiaWF0IjoxNjI5MDUyMTU0LCJleHAiOjE2MjkwNzAxNTR9.DJzaDCWmevScIYyEWM36yJoPClOVB5v2Lf97UaD15cI

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "No Token",
  "author": "A. Miller",
  "url": "http://noToken.html",
  "likes": "10"
}
