POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE5MTk5NDBmYzJkNDBkMmVjMWM1ZWEiLCJpYXQiOjE2MjkwMzQ5MTYsImV4cCI6MTYyOTA1MjkxNn0.veWmdXP596H1RTWJoAJC-OoYoe68TqjpOf95iD3f7NE

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": "5"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE5MTk5NDBmYzJkNDBkMmVjMWM1ZWEiLCJpYXQiOjE2MjkwMzQ5MTYsImV4cCI6MTYyOTA1MjkxNn0.veWmdXP596H1RTWJoAJC-OoYoe68TqjpOf95iD3f7NE

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": "7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTE5OTUwZmMyZDQwZDJlYzFjNWVlIiwiaWF0IjoxNjI5MDM0OTQ3LCJleHAiOjE2MjkwNTI5NDd9.CzeF--pTpM0Hza40JxVw4knAU_3WffiIGbF_X0TRF2Y

{
  "title": "Canonical string reduction",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
  "likes": "12"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTE5OTUwZmMyZDQwZDJlYzFjNWVlIiwiaWF0IjoxNjI5MDM0OTQ3LCJleHAiOjE2MjkwNTI5NDd9.CzeF--pTpM0Hza40JxVw4knAU_3WffiIGbF_X0TRF2Y

{
  "title": "First class tests",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.html",
  "likes": "10"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTE5OTUwZmMyZDQwZDJlYzFjNWVlIiwiaWF0IjoxNjI5MDM0OTQ3LCJleHAiOjE2MjkwNTI5NDd9.CzeF--pTpM0Hza40JxVw4knAU_3WffiIGbF_X0TRF2Y

{
  "title": "TDD harms architecture",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
  "likes": "0"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9wZXJleiIsImlkIjoiNjExOTE5OTUwZmMyZDQwZDJlYzFjNWVlIiwiaWF0IjoxNjI5MDM0OTQ3LCJleHAiOjE2MjkwNTI5NDd9.CzeF--pTpM0Hza40JxVw4knAU_3WffiIGbF_X0TRF2Y

{
  "title": "Type wars",
  "author": "Robert C. Martin",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}
