DELETE http://localhost:3003/api/blogs/61195d0bcbcd8a1d9a37a9cb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFpcmlzIiwiaWQiOiI2MTE5NWNlM2NiY2Q4YTFkOWEzN2E5YzAiLCJpYXQiOjE2MjkwNTIxMzksImV4cCI6MTYyOTA3MDEzOX0.NlC6hT-kbBMSftlQnwsaTfbJTdJk8zvAngY5HP3NXdE
